<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_product_manager"
 *
 * Auto generated by Extension Builder 2014-07-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Products Manager',
    'description' => 'Allow to create and list products on a site.',
    'category' => 'plugin',
    'author' => 'Andriy Oprysko',
    'author_email' => '',
    'author_company' => '',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => true,
    'version' => '8.8.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7'
        ],
        'conflicts' => [],
        'suggests' => []
    ]
];
